baseURL = "https://from-the-kitchen-of.netlify.app/recipes/"
languageCode = "en-us"
title = "From The Kitchen Of"
theme = "PaperMod"

[params]
  defaultTheme = "dark"

[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 20